---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ota-tuf-keyserver.fullname" . }}
  labels:
    app: {{ template "ota-tuf-keyserver.name" . }}
    chart: {{ template "ota-tuf-keyserver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_ENCRYPTION_PASSWORD: {{ .Values.secret.DB_ENCRYPTION_PASSWORD | b64enc }}
  DB_ENCRYPTION_SALT: {{ .Values.secret.DB_ENCRYPTION_SALT | b64enc }}
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc }}
