---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crypt-vault-config
data:
  DEFAULT_LEASE_TTL: 30s
  MAX_LEASE_TTL: 30s
  MYSQL_ADDR: {{ .mysql_host }}:3306
  MYSQL_DATABASE: crypt_vault
  MYSQL_DATABASE_TABLE: crypt_vault
  MYSQL_USERNAME: {{ .crypt_vault_db_user }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypt-vault
spec:
  selector:
    matchLabels:
      app: crypt-vault
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: crypt-vault
    spec:
      containers:
      - name: crypt-vault
        image: {{ .crypt_vault_docker_image }}
        envFrom:
        - configMapRef:
            name: crypt-vault-config
        - secretRef:
            name: crypt-vault-secret
        ports:
        - containerPort: 8200
        resources:
          requests:
            cpu: {{.crypt_vault_cpu}}
            memory: {{.crypt_vault_mem}}
        livenessProbe:
          initialDelaySeconds: 300
          periodSeconds: 30
          tcpSocket:
            port: 8200
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
---
apiVersion: v1
kind: Secret
metadata:
  name: crypt-vault-secret
type: Opaque
data:
  MYSQL_PASSWORD: {{ .crypt_vault_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: crypt-vault
spec:
  ports:
  - port: 80
    targetPort: 8200
  selector:
    app: crypt-vault
