---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "ota-director.fullname" . }}-daemon
  labels:
    app: {{ template "ota-director.name" . }}-daemon
    chart: {{ template "ota-director.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "ota-director.name" . }}-daemon
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-daemon
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          envFrom:
          - configMapRef:
              name: {{ template "ota-director.fullname" . }}
          - secretRef:
              name: {{ template "ota-director.fullname" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.configMap.BIND_PORT }}
              name: http
          args:
            - "-main"
            - com.advancedtelematic.director.daemon.DaemonBoot
          livenessProbe:
            initialDelaySeconds: 300
            periodSeconds: 30
            httpGet:
              path: "/health"
              port: {{ .Values.configMap.BIND_PORT }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
