---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ota-director.fullname" . }}
  labels:
    app: {{ template "ota-director.name" . }}
    chart: {{ template "ota-director.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc }}
