{{- if .Values.ingress.internalIngressEnabled -}}
{{- $serviceName := include "ota-tuf-reposerver.fullname" . -}}
{{- $servicePort := .Values.service.publicTufReposerverPort -}}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "ota-tuf-reposerver.fullname" . }}-internal
  labels:
    app: {{ template "ota-tuf-reposerver.name" . }}
    chart: {{ template "ota-tuf-reposerver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    {{- range $host := .Values.ingress.internalHosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ $serviceName }}-internal
              servicePort: {{ $servicePort }}
    {{- end -}}
  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
{{- end -}}
