replicaCount: 1
image:
  repository: advancedtelematic/director
  tag: latest
  pullPolicy: Always

configMap:
  BIND_PORT: '9001'
  BIND_HOST: '0.0.0.0'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://ota-mariadb:3306/director
  DB_USER: director
  ENV_PREFIX: ota_
  JAVA_OPTS: '-XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2'
  KAFKA_BOOTSTRAP_SERVERS: ota-kafka:9092
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: "false"
  SOTA_CORE_HOST: ota-sota-core
  SOTA_CORE_PORT: '80'
  TUF_KEYSERVER_HOST: ota-tuf-keyserver
  TUF_KEYSERVER_PORT: '80'
  TUF_REPOSERVER_HOST: ota-tuf-reposerver-internal
  TUF_REPOSERVER_PORT: '80'
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"

secret:
  DB_PASSWORD: director

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - director.ota.local
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  tls: []

proxy:
  allow: false

resources:
  requests:
    cpu: 200m
    memory: 200Mi
