---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tuf-keyserver-daemon-config
data:
  BIND_PORT: '9001'
  DB_MIGRATE: 'true'
  DB_URL: jdbc:mariadb://{{ .mysql_host }}:3306/tuf_keyserver
  DB_USER: {{ .tuf_keyserver_daemon_db_user }}
  JAVA_OPTS: {{ .tuf_keyserver_java_opts }}
  REPORT_METRICS: "false"
  TUF_VAULT_HOST: tuf-vault
  TUF_VAULT_PORT: '80'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tuf-keyserver-daemon
spec:
  selector:
    matchLabels:
      app: tuf-keyserver-daemon
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: tuf-keyserver-daemon
    spec:
      containers:
      - name: tuf-keyserver-daemon
        image: {{ .tuf_keyserver_daemon_docker_image }}
        args:
        - "-main"
        - com.advancedtelematic.tuf.keyserver.daemon.KeyGenerationDaemon
        envFrom:
        - configMapRef:
            name: kafka-shared
        - configMapRef:
            name: tuf-keyserver-daemon-config
        - secretRef:
            name: tuf-keyserver-daemon-secret
        - secretRef:
            name: tuf-tokens
        ports:
        - containerPort: 9001
        resources:
          requests:
            cpu: {{ .tuf_keyserver_daemon_cpu }}
            memory: {{ .tuf_keyserver_daemon_mem }}
        livenessProbe:
          initialDelaySeconds: 60
          periodSeconds: 30
          httpGet:
            port: 9001
            path: "/health"
---
apiVersion: v1
kind: Secret
metadata:
  name: tuf-keyserver-daemon-secret
type: Opaque
data:
  DB_PASSWORD: {{ .tuf_keyserver_daemon_db_password | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: tuf-keyserver-daemon
spec:
  ports:
  - port: 80
    targetPort: 9001
  selector:
    app: tuf-keyserver-daemon
