replicaCount: 1

image:
  repository: advancedtelematic/device-registry
  tag: latest
  pullPolicy: Always

configMap:
  AUTH_PROTOCOL: 'none'
  AUDITOR_HOST: ota-auditor
  AUDITOR_PORT: 80
  BIND_HOST: 0.0.0.0
  BIND_PORT: 9001
  DB_MIGRATE: true
  DB_URL: jdbc:mariadb://ota-mariadb:3306/device_registry
  DB_USER: device_registry
  DIRECTOR_HOST: ota-director
  DIRECTOR_PORT: 80
  ENV_PREFIX: ota_
  JAVA_OPTS: -XshowSettings:vm -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=2
  KAFKA_BOOTSTRAP_SERVERS: ota-kafka:9092
  KAFKA_HOST: ota-kafka:9092
  KAFKA_TOPIC_SUFFIX: ota
  LOG_APPENDER: async_json
  REPORT_METRICS: false
  ATS_HTTP_TRACING: "true"
  ZIPKIN_URI: "http://ota-zipkin:9411"

service:
  type: ClusterIP
  port: 80

secret:
  DB_PASSWORD: device_registry

ingress:
  enabled: false
  annotations:
    kubernetes.io/ingress.class: nginx
  path: /
  hosts:
    - device-registry.ota.local
  tls: []

proxy:
  allow: false

resources:
  requests:
    cpu: 80m
    memory: 300Mi

privateRegistry: false

registryPullSecrets: docker-registry-key

nodeSelector: {}

tolerations: []

affinity: {}
