---
apiVersion: v1
kind: Secret
metadata:
  name: {{ print "jwt-signing-key-" .Values.nameOverride | trimSuffix "-" }}
  labels:
    app: {{ template "ota-app.name" . }}
    chart: {{ template "ota-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  jwt-signing-key: {{ .Values.secret.JWT_SECRET | b64enc }}
