{{- if .Values.secret.AUTHPLUS_CLIENT_ID }}
{{- if .Values.secret.AUTHPLUS_CLIENT_SECRET }}
---
apiVersion: v1
data:
  client_id: {{ .Values.secret.AUTHPLUS_CLIENT_ID | b64enc }}
  client_secret: {{ .Values.secret.AUTHPLUS_CLIENT_SECRET | b64enc }}
kind: Secret
metadata:
  name: auth-plus-client-treehub
  labels:
    app: {{ template "ota-treehub.name" . }}
    chart: {{ template "ota-treehub.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
{{- end -}}
{{- end -}}
