---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ota-treehub.fullname" . }}
  labels:
    app: {{ template "ota-treehub.name" . }}
    chart: {{ template "ota-treehub.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  DB_PASSWORD: {{ .Values.secret.DB_PASSWORD | b64enc }}
{{- if eq .Values.configMap.TREEHUB_STORAGE "s3" }}
  TREEHUB_AWS_ACCESS_KEY: {{ .Values.secret.TREEHUB_AWS_ACCESS_KEY | b64enc }}
  TREEHUB_AWS_SECRET_KEY: {{ .Values.secret.TREEHUB_AWS_SECRET_KEY | b64enc }}
{{- end }}
