---
env_prefix: ce
ingress_acl_whitelist: 0.0.0.0/0
ingress_dns_name: ota.local
ingress_proxy_size: 300m
kafka_host: kafka
kafka_topic_suffix: ce
mysql_host: mysql
persistent_volumes: true
storage_class_name: ""
zookeeper_host: zookeeper
