{{- if .Values.secret.CLIENT_ID }}
{{- if .Values.secret.CLIENT_SECRET }}
---
apiVersion: v1
data:
  client_id: {{ .Values.secret.CLIENT_ID | b64enc }}
  client_secret: {{ .Values.secret.CLIENT_SECRET | b64enc }}
kind: Secret
metadata:
  name: auth-plus-client-api-gateway
  labels:
    app: {{ template "ota-api-gateway.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
{{- end -}}
{{- end -}}
