{{- if .Values.configMap.connect.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ota-app.fullname" . }}-connect
  labels:
    app: {{ template "ota-app.name" . }}
    chart: {{ template "ota-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AUTH0_CLIENT_ID: {{ .Values.secret.connect.AUTH0_CLIENT_ID | b64enc }}
  AUTH0_CLIENT_SECRET: {{ .Values.secret.connect.AUTH0_CLIENT_SECRET | b64enc }}
  OIDC_KEYSET: {{ .Values.secret.connect.OIDC_KEYSET | b64enc }}
{{- end -}}
