---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ota-app.fullname" . }}
  labels:
    app: {{ template "ota-app.name" . }}
    chart: {{ template "ota-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  PLAY_CRYPTO_SECRET: {{ .Values.secret.PLAY_CRYPTO_SECRET | b64enc }}
  {{- if .Values.configMap.atsgarage.enabled }}
  AUTH0_AUTH_PLUS_CLIENT_ID: {{ .Values.secret.AUTH0_AUTH_PLUS_CLIENT_ID | b64enc }}
  AUTH0_USER_UPDATE_TOKEN: {{ .Values.secret.AUTH0_USER_UPDATE_TOKEN | b64enc }}
  {{- end -}}
