apiVersion: v1
kind: Secret
metadata:
  name: {{ template "ota-mariadb.fullname" . }}
  labels:
    app: {{ template "ota-mariadb.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.secret.MYSQL_ROOT_PASSWORD | b64enc }}
