---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ota-tuf-reposerver.fullname" . }}-internal
  labels:
    app: {{ template "ota-tuf-reposerver.name" . }}-internal
    chart: {{ template "ota-tuf-reposerver.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.internalTufReposerverType }}
  ports:
    - port: {{ .Values.service.internalTufReposerverPort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "ota-tuf-reposerver.name" . }}-internal
    release: {{ .Release.Name }}
