apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "ota-device-registry.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "ota-device-registry.fullname" . }}
  minReplicas: {{ .Values.HorizontalPodAutoscaler.minReplicas }}
  maxReplicas: {{ .Values.HorizontalPodAutoscaler.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.HorizontalPodAutoscaler.averageUtilization }}

