replicaCount: 1
image:
  repository: advancedtelematic/api-gateway
  tag: latest
  pullPolicy: Always

configMap:
  DIRECTOR_HOST: ota-director
  DIRECTOR_PORT: '80'
  JWT_ISS_PATTERN: 'https://auth-plus.advancedtelematic.com'
  NGINX_DEBUG_LEVEL: warn
  TREEHUB_HOST: ota-treehub-internal
  TREEHUB_HOST_PUB: ota-treehub
  TREEHUB_PORT: '80'
  TREEHUB_PORT_PUB: '80'
  TUF_REPOSERVER_HOST: ota-tuf-reposerver-internal
  TUF_REPOSERVER_HOST_PUB: ota-tuf-reposerver
  TUF_REPOSERVER_PORT: '80'
  TUF_REPOSERVER_PORT_PUB: '80'

timeouts: 120

secret: {}
  # youshouldreplacethiswithsomeotherlongsecret in base64

service:
  type: ClusterIP
  apiGatewayInternalPort: 80
  apiGatewayExternalPort: 80
  # These can be set when using the LoadBalancer type on a non-local setup:
  # internal: true
  # sslCert: arn:aws:iam::123456787890:server-certificate/cert-name
  # sslPorts: "*"
  # dnsName: api-gateway.ota.local

ingress:
  enabled: true
  hosts:
    - api-gateway.ota.local
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-body-size: 3072m
  tls: []

proxyServices:
  - ota-director
  - ota-tuf-reposerver
  - ota-treehub

resources:
  requests:
    cpu: 100m
    memory: 300Mi

privateRegistry: true
registryPullSecret: docker-registry-key


